### ISSUE TITLE
easysnmp.exceptions.EasySNMPConnectionError: couldn't create SNMP handle on Solaris 11

### ISSUE THREAD

**Issue by jshutich** [easysnmp/easysnmp#111]
I have netsnmp-5.8 installed on a Solaris 11 machine. I have python 3.5.6 installed and easysnmp installed.

I can do 
snmpget -v 2c -c public 10.216.86.125 '1.3.6.1.2.1.1.1.0' '1.3.6.1.2.1.1.2.0' '1.3.6.1.2.1.1.5.0'
no problem
which snmpget
/home/appl/netsnmp-5.8/bin/snmpget
ldd /home/appl/netsnmp-5.8/bin/snmpget
        libnetsnmp.so.35 =>      /home/appl/netsnmp-5.8/lib/libnetsnmp.so.35
        libkstat.so.1 =>         /lib/64/libkstat.so.1
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libcrypto.so.1.0.0 =>    /lib/64/libcrypto.so.1.0.0
        libelf.so.1 =>   /lib/64/libelf.so.1
        libm.so.2 =>     /lib/64/libm.so.2
        libc.so.1 =>     /lib/64/libc.so.1
        libz.so.1 =>     /lib/64/libz.so.1

the easysnmp interface.so shows
/home/appl/perl/python/VirtualEnvs/netexpert356/lib/python3.5/site-packages/easysnmp-0.2.5-py3.5-solaris-2.11-sun4v.64bit.egg/easysnmp> ldd interface.so
        libnetsnmp.so.35 =>      /home/appl/netsnmp-5.8/lib/libnetsnmp.so.35
        libkstat.so.1 =>         /lib/64/libkstat.so.1
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libcrypto.so.1.0.0 =>    /lib/64/libcrypto.so.1.0.0
        libelf.so.1 =>   /lib/64/libelf.so.1
        libm.so.2 =>     /lib/64/libm.so.2
        libc.so.1 =>     /lib/64/libc.so.1
        libz.so.1 =>     /lib/64/libz.so.1

So when I do
Python 3.5.6 (default, Aug 25 2018, 01:48:21) 
[GCC 5.4.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> from easysnmp import Session
>>> sys_descr = '1.3.6.1.2.1.1.1.0'
>>> sys_object_id = '1.3.6.1.2.1.1.2.0'
>>> sys_contact = '1.3.6.1.2.1.1.4.0'
>>> sys_name = '1.3.6.1.2.1.1.5.0'
>>> ip_forwarding = '1.3.6.1.2.1.4.1.0'
>>> snmp_engineid = '1.3.6.1.6.3.10.2.1.1.0'
>>> oid_list = [sys_descr, sys_object_id, sys_contact, sys_name, ip_forwarding, snmp_engineid]
>>> hostname = '10.216.86.125'
>>> community= 'public'
>>> session = Session(hostname=hostname, community=community, version=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/appl/perl/python/VirtualEnvs/netexpert356/lib/python3.5/site-packages/easysnmp-0.2.5-py3.5-solaris-2.11-sun4v.64bit.egg/easysnmp/session.py", line 286, in __init__
    timeout_microseconds
easysnmp.exceptions.EasySNMPConnectionError: couldn't create SNMP handle
>>> quit()

I'm not understanding why easysnmp can't create the handle.

BTW, we also have Linux machines and have no issues with easysnmp on them. Same version of python, just one for Linux and one for Solaris.

Any help is appreciated.

John

**Comment by jshutich** [comment]
I removed the interface.so from a subdirectory of the build directory, rebuilt it and now it is working.
