### ISSUE TITLE
[BUG] unable to compile on RHEL7 (possibly revealing deeper bug)

### ISSUE THREAD

**Issue by uedvt359** [easysnmp/easysnmp#154]
**EasySNMP release version OR commit number**
0.2.6a

**Operating System and Version**
 - OS: RHEL
 - Version 7.9

**Net-SNMP Library Version**
 - 5.7.2 (net-snmp-devel-5.7.2-49.el7_9.1.x86_64)

**Describe the bug**

easysnmp doesn't compile under RHEL7. The relevant lines:
```
easysnmp/interface.c: In function __match_algo:
easysnmp/interface.c:128:23: error: usmHMAC128SHA224AuthProtocol undeclared (first use in this function)
easysnmp/interface.c:135:23: error: usmHMAC192SHA256AuthProtocol undeclared (first use in this function) 
easysnmp/interface.c:144:23: error: usmHMAC256SHA384AuthProtocol undeclared (first use in this function)
easysnmp/interface.c:151:23: error: usmHMAC384SHA512AuthProtocol undeclared (first use in this function)
```

I believe this might be an issue with how easysnmp uses the `HAVE_EVP_SHA224`, `HAVE_EVP_SHA384`, etc `#define`s in `/usr/include/net-snmp/net-snmp-config-x86_64.h`: easysnmp checks for defined-ness, not value. however, net-snmp defines these macros to equal `1` if it exists, and `/**/` otherwise -- so easysnmp's check always succeeds.

This is probably a problem will all the macros used from this header. 

**To Reproduce**
1. use a version of net-snmp-libs that doesn't support all algorithms
2. try to compile easysnmp

**Expected behavior**
the unsupported algorithms should not try to be compiled.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by kamakazikamikaze** [comment]
This may not strictly be a RHEL7 issue. Our GA workflow is just downloading the latest Net-SNMP package from official repos (5.8) and OpenSSL. We'll need to check if the macro `#define` lines are indeed the culprit and test against 5.7.2 if previous OS versions (RHEL/CentOS 7, Ubuntu 18.04) are pinned against that.

**Comment by jbackman** [comment]
FYI - I was able to build by modifying the `net-snmp-config-x86_64.h` file:
`sed -i '/#define HAVE_EVP_SHA/d' /usr/include/net-snmp/net-snmp-config-x86_64.h `

Yes this is the hammer approach...

**Comment by kamakazikamikaze** [comment]
> Yes this is the hammer approach...

Haha! I was going to say, that probably works but probably wouldn't be something I'd recommend for everyone on CentOS/RHEL 7.x 😆

I'll compare 5.7, 5.8, and 5.9 to see their definitions and we can tweak the directives a bit to look for definedness, value 0, or value 1. I'll make a CentOS 7 VM to facilitate my testing.

**Comment by jbackman** [comment]
Actually - the issue has to do with how net-snmp compiles with openssl. If you have the latest openssl, this would not be an issue as the required functionality would be there. RHEL 7 ships with an older version of openssl which when you compile the 5.7.x version of net-snmp, will cause those variables to be defined incorrectly.

**Comment by baltimorestrings** [comment]
Another workaround for this issue is simply installing net-snmp-5.8

In my case this wasn't available as a yum package (work managed systems), so I built net-snmp-5.8 from source, then ran pip install with the CPATH pointing at the include folder in the source like so:

```bash
> CPATH=/home/baltimorestrings/ns/net-snmp-5.8/include/ && pip install easysnmp -q && echo success
success
>
```
Seems like easysnmp requires netsnmp-5.8+ now and the docs are lagging behind? Or am I misunderstanding.

**Comment by ShyrusX** [comment]
Hi Guys,

Facing similar issue. I tried to install easysnmp 0.2.6 on RHEL7, but it aborts. NET-SNMP 5.8 installed on that system.
Then I tried it on Ubuntu 22.04. NET-SNMP 5.9.1 installed. It is installed but it tells me for everything else then MD5 or SHA
 "ValueError: unsupported authentication protocol (SHA-512)"


```
>>> session = Session(hostname="192.168.0.10", version=3, timeout=5, retries=3, security_level="auth_with_privacy", security_username="MYUSER", privacy_protocol="AES128", privacy_password="MYPASS", auth_protocol="SHA-512", auth_password="MYPASS")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/easysnmp/session.py", line 265, in __init__
    self.update_session()
  File "/usr/local/lib/python3.10/dist-packages/easysnmp/session.py", line 536, in update_session
    self.sess_ptr = interface.session_v3(
ValueError: unsupported authentication protocol (SHA-512)
```


When I directly use the Shell with "snmpget" command and enter all the values above, it works just fine:

shyrus@ProgUbuntu:/tmp$ sudo snmpget -v3 -u MYUSER -l authPriv -a SHA-512 -A MYPASS -x AES128 -X MYPASS 192.168.0.10 1.3.6.1.2.1.1.3.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (68676412) 7 days, 22:46:04.12
shyrus@ProgUbuntu:/tmp$

Is there already a solution for this one? :-)

Greetings
Shyrus

**Comment by egroeper** [comment]
> I tried it on Ubuntu 22.04. NET-SNMP 5.9.1 installed. It is installed but it tells me for everything else then MD5 or SHA "ValueError: unsupported authentication protocol (SHA-512)"

> When I directly use the Shell with "snmpget" command and enter all the values above, it works just fine:
> 
> shyrus@ProgUbuntu:/tmp$ sudo snmpget -v3 -u MYUSER -l authPriv -a SHA-512 -A MYPASS -x AES128 -X MYPASS 192.168.0.10 1.3.6.1.2.1.1.3.0 iso.3.6.1.2.1.1.3.0 = Timeticks: (68676412) 7 days, 22:46:04.12 shyrus@ProgUbuntu:/tmp$
> 
> Is there already a solution for this one? :-)

Sounds like the problem I just got. I resolved it by **not using** the provided **wheel** easysnmp-0.2.6-cp38-cp38-manylinux_2_24_x86_64.whl, which seems to be build against something not supporting those algos, but compiled from source instead:

`pip install --force-reinstall --no-binary :all: easysnmp`

This solved it for me on Ubuntu 20.04.
