### ISSUE TITLE
[BUG] Failing installation on M3 MacBook MacOS 14.4

### ISSUE THREAD

**Issue by joseftschiggerlnts** [easysnmp/easysnmp#200]
**EasySNMP release version OR commit number**
0.2.6 (pip)

**Operating System and Version**
 - OS: MacOS 
 - Version 14.4.1
 - Macbook Pro M3

**Net-SNMP Library Version**
 - 5.9.4 (brew)

**Describe the bug**
I am facing issues installing easysnmp on my Macbook Pro M3 with MacOS 14.4.1 using Python 3.12.3 (tried it with Python 3.10 as well)
I installed net-snmp (net-snmp: stable 5.9.4) using brew.

```
pip install easysnmp
Collecting easysnmp
  Using cached easysnmp-0.2.6.tar.gz (43 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running egg_info
      writing easysnmp.egg-info/PKG-INFO
      writing dependency_links to easysnmp.egg-info/dependency_links.txt
      writing top-level names to easysnmp.egg-info/top_level.txt
      reading manifest file 'easysnmp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'easysnmp.egg-info/SOURCES.txt'
      error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: build/lib.macosx-14.0-arm64-cpython-312/easysnmp/interface.cpython-312-darwin.so (No such file or directory)
      Traceback (most recent call last):
        File "/Users/user/Documents/work/git/worker/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/Documents/work/git/worker/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/Documents/work/git/worker/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bv/6wv0s4z956x4nrhqh34w_qjm0000gp/T/pip-build-env-887rvdst/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bv/6wv0s4z956x4nrhqh34w_qjm0000gp/T/pip-build-env-887rvdst/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/bv/6wv0s4z956x4nrhqh34w_qjm0000gp/T/pip-build-env-887rvdst/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/bv/6wv0s4z956x4nrhqh34w_qjm0000gp/T/pip-build-env-887rvdst/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 179, in <module>
      NameError: name 'target_lib' is not defined. Did you mean: 'target_libs'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**To Reproduce**
`pip install easysnmp`

**Expected behavior**
Successfull installation

**Screenshots**
-

**Additional context**
 - Tried with Python 3.12.3 and 3.10

**Comment by joseftschiggerlnts** [comment]
Based on my research this looks similar to https://github.com/easysnmp/easysnmp/issues/171#issuecomment-1221933127
Unfortunately the the hints in this thread didn't help me :( 
Maybe @denisbondar knows whats going on? :)

**Comment by denisbondar** [comment]
@joseftschiggerlnts I was able to successfully install directly from the repository as follows:
```shell
pip install https://github.com/easysnmp/easysnmp/archive/testing.zip
```

It's worth mentioning that I gave up using this library a long time ago, as unfortunately it looks neglected and existing serious bugs are not being addressed. I recommend you to find an alternative.

**Comment by joseftschiggerlnts** [comment]
Thank you @denisbondar for getting back to me this quickly! 
Will do that ...

**Comment by mjbogusz** [comment]
Posting for visibility/searchability:
* Main issue regarding Python 3.11+: https://github.com/easysnmp/easysnmp/issues/185
  * related to building for Mac/ARM as there is some very custom code in setup.py when targeting MacOS
* PR with some discussion: https://github.com/easysnmp/easysnmp/pull/186
* Updated and maintained fork (also available in pip): https://github.com/carlkidcrypto/ezsnmp
