### ISSUE TITLE
Python 3.12 and imp library

### ISSUE THREAD

**Issue by Challado** [easysnmp/easysnmp#202]
Debian now uses python 3.12, and when you will run easysnmp we have these error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pysnmp/smi/builder.py", line 19, in <module>
    SOURCE_SUFFIXES = importlib.machinery.SOURCE_SUFFIXES
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'machinery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pysnmp/smi/builder.py", line 23, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/servidor/scripts/rondotec-cron.py", line 8, in <module>
    from pysnmp.hlapi import *;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pysnmp/hlapi/__init__.py", line 9, in <module>
    from pysnmp.smi.rfc1902 import *
  File "/usr/lib/python3/dist-packages/pysnmp/smi/rfc1902.py", line 10, in <module>
    from pysnmp.smi.builder import ZipMibSource
  File "/usr/lib/python3/dist-packages/pysnmp/smi/builder.py", line 26, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by wangxin688** [comment]
https://github.com/carlkidcrypto/ezsnmp fork should be working

**Comment by lextm** [comment]
You posted to the wrong repo @Challado 

PySNMP is covered by https://github.com/lextudio/pysnmp, not here.
