### ISSUE TITLE
[BUG] bulkwalk runs indefinitely when encountering a non-increasing OID

### ISSUE THREAD

**Issue by eoswald** [easysnmp/easysnmp#205]
**EasySNMP release version OR commit number**
0.2.6

**Operating System and Version**
 - OS: Red Hat Enterprise Linux release
 - Version 8.8 (Ootpa)

**Net-SNMP Library Version**
I think this is how to get it?
 ```
 $ snmpbulkwalk --version
NET-SNMP version: 5.8
```

**Describe the bug**
When performing a `session.bulkwalk` on a device's OID that is not increasing, the `max_repetitions` kwarg does not seem to be respected and the bulkwalk indefinitely tries to get the next OID. When using the `snmpbulkwalk` command, it behaves fine:

```
$ snmpbulkwalk -v 2c -c ***** -Dsnmp X.X.X.X 1.0.8802.1.1.2.1.4.1.1.4 -Cr10
registered debug token snmp, 1
snmp_parse_args: handling (#9): C (optarg r10) (sp 0)
snmp_parse_args: finished: 7/9
snmp_alarm: no alarms found to schedule
snmp_sess: opening transport: 0
snmp_sess: limiting session rcv size to transport max
snmp_sess: limiting session snd size to transport max
snmp_sess: done opening transport: 20
snmp_sess: opening transport: 20
snmp_sess_add: fd 3
snmp_send: Building SNMPv2 message...
snmp_pdu_realloc_rbuild: starting
snmp_api: Parsing SNMPv2 message...
snmp_synch: Response (ReqID: 1350871382 - Cmd 162)
snmp_synch: status = 0 errno = 0
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
snmp_send: Building SNMPv2 message...
snmp_pdu_realloc_rbuild: starting
snmp_api: Parsing SNMPv2 message...
snmp_synch: Response (ReqID: 1350871383 - Cmd 162)
snmp_synch: status = 0 errno = 0
iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13

iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13 = INTEGER: 4
Error: OID not increasing: iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
 >= iso.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
```

However, the following python script will run forever. When I Ctrl-C the script it results in a segfault:

```python
# test_easysnmp.py
import logging

from easysnmp import Session


logging.basicConfig(level=logging.DEBUG)
session = Session(version=2, community="*****", security_username="*****", security_level="no_auth_or_privacy", auth_password="", context="", timeout=1.3, retries=0, hostname="X.X.X.X", use_sprint_value=True, use_numeric=True)
session.bulkwalk("1.0.8802.1.1.2.1.4.1.1.4", max_repetitions=10)
```

```
$ python test_easysnmp.py
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Starting
DEBUG:easysnmp.interface:netsnmp_bulkwalk: nonreps (0) max_reps (10)
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Getting initial oids
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Initial oid(1.0.8802.1.1.2.1.4.1.1.4) oid_idx()
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Starting bulk walk request
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Sending pdu req
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Finished reading all variables for req
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Sending pdu req
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Finished reading all variables for req
...
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Sending pdu req
^CSegmentation fault (core dumped)
```

**To Reproduce**
```
mkdir test_easysnmp
cd test_easysnmp
vim test_easysnmp.py  # copy contents above
python3.9 -m venv venv  # also tested with python3.10
source ./venv/bin/activate
pip install easysnmp==0.2.6
python test_easysnmp.py
```

**Expected behavior**
I expect the to only see 10 (if `max_repetitions=10`) "Sending pdu req" log messages and the program to gracefully exit.

**Comment by eoswald** [comment]
Apologies, I was mistaken. It seems like `maxrepetitions` _is_ being respected since it repeats within the pdu request. I am not sure what is causing this loop. Still investigating.

**Comment by eoswald** [comment]
Below is a sanitized core dump:
```
    (Python) File "/root/test_easysnmp.py", line 8, in <module>
    (Python) File 
"*****/python/lib/python3.10/site-packages/easysnmp/session.py", line 478, in bulkwalk
        interface.bulkwalk(self, non_repeaters, max_repetitions, varlist)
      Arguments:
        max_repetitions: 10
        non_repeaters: 0
        oids: "1.0.8802.1.1.2.1.4.1.1.4"
        self: <Session at 0x7fc18410b970>
      Locals:
        _: False
        varlist: [<SNMPVariable at 0x7fc18412f580>, <SNMPVariable at 0x7fc18417c3d0>, ...]
    (C) File "*****/python/python3.10/Objects/methodobject.c", line 552, in cfunction_call (libpython3.10.so.1.0)
    (C) File "easysnmp/interface.c", line 3709, in netsnmp_bulkwalk (interface.cpython-310-x86_64-linux-gnu.so)
    (C) File "*****/python/python3.10/Objects/object.c", line 823, in PyObject_HasAttrString (libpython3.10.so.1.0)
    (C) File "*****/python/python3.10/Objects/object.c", line 810, in PyObject_GetAttrString (libpython3.10.so.1.0)
```

**Comment by eoswald** [comment]
I built this locally with debug symbols and found that it's segfaulting at this line: https://github.com/easysnmp/easysnmp/blob/d01417776f49aa172cb1342f064844fd76403cc5/easysnmp/interface.c#L3691

```
DEBUG:easysnmp.interface:netsnmp_bulkwalk: !is_leaf: 0
DEBUG:easysnmp.interface:netsnmp_bulkwalk: str_buf: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51.13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: filling response: .1.0.8802.1.1.2.1.4.1.1.4.989262276.51:13
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Finished reading all variables for req
DEBUG:easysnmp.interface:netsnmp_bulkwalk: Sending pdu req
^C
Program received signal SIGINT, Interrupt.
0x00007ffff65ff1bb in select () from /lib64/libc.so.6
(gdb) signal 2
Continuing with signal SIGINT.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b652dc in PyObject_GetAttrString (v=0x0, name=0x7ffff7e1fb42 "oid") at /.../python/python3.9/Objects/object.c:790
790	/.../python/python3.9/Objects/object.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff7b652dc in PyObject_GetAttrString (v=0x0, name=0x7ffff7e1fb42 "oid") at /.../python/python3.9/Objects/object.c:790
#1  0x00007ffff7b15176 in PyObject_HasAttrString (v=<optimized out>, name=<optimized out>) at /.../python/python3.9/Objects/object.c:803
#2  0x00007ffff7e1d656 in netsnmp_bulkwalk (self=0x7ffff63c3f40, args=0x7ffff634f400) at easysnmp/interface.c:3691
...
```

```
3689                        varbind = py_netsnmp_construct_varbind();
3690
3691                        if (PyObject_HasAttrString(varbind, "oid"))
```

https://github.com/easysnmp/easysnmp/blob/d01417776f49aa172cb1342f064844fd76403cc5/easysnmp/interface.c#L1408-L1411

I believe the issue is that the Python garbage collector is freeing `easysnmp_import` so `PyObject_CallMethod` errors and returns `NULL`. However, I'm not entirely sure why SIGINT isn't interrupting the C code. Maybe the Python garbage collector is acting faster?

I've never worked with Python C bindings before so I don't know what the proper way to handle this would be. Should the C code hold a reference to `easysnmp_import`?
