### ISSUE TITLE
snmp_set not working

### ISSUE THREAD

**Issue by franchuk82** [easysnmp/easysnmp#76]
Hi. i am use easysnmp==0.2.4 and i try do snmp_set with type='STRING', but id doesn't work

do like this 

```
from easysnmp import snmp_set
res = snmp_set(
    oid='iso.3.6.1.2.1.10.94.1.1.1.1.4.7',
    value=str('1024Kb'),
    type='STRING',
    hostname='192.168.122.14',
    remote_port=161,
    community='RhenjqRtq',
    version=2
)
```
and had got that response
```
Traceback (most recent call last):
  File "/home/oleg/PycharmProjects/Billing-dhcp/scripts/1.py", line 10, in <module>
    version=2
  File "/home/oleg/venv/billing-dhcp/local/lib/python2.7/site-packages/easysnmp/easy.py", line 43, in snmp_set
    return session.set(oid, value, type)
  File "/home/oleg/venv/billing-dhcp/local/lib/python2.7/site-packages/easysnmp/session.py", line 348, in set
    success = interface.set(self, varlist)
easysnmp.exceptions.EasySNMPUndeterminedTypeError: a type could not be determine for the object
```
from command line 
`snmpset -v 2c -c RhenjqRtq 192.168.122.14 iso.3.6.1.2.1.10.94.1.1.1.1.4.7 s '2048Kb'`
does work perfect

with type='INTEGER' all work good

what i had done wrong and why it's doesn't work?

**Comment by drscholl78** [comment]
I've the same issue, did you find a solution?
